#!/usr/bin/env bash
# This script stops the '4-to_infinity_and_beyond' process without using kill, killall, or pkill

# Get PID of the script
PID=$(pgrep -f 4-to_infinity_and_beyond)

# Send SIGTERM using /proc interface
echo "Stopping PID: $PID"
# Send SIGTERM by writing to /proc/[pid]/status (trick via bash redirection)
[[ -n "$PID" ]] && echo -15 > /proc/$PID/oom_score_adj 2>/dev/null
