#!/usr/bin/env bash
# Find the PID of the 4-to_infinity_and_beyond script
PID=$(pgrep -f "./4-to_infinity_and_beyond")
# Use gdb to attach and send a SIGTERM without using kill or killall
if [ -n "$PID" ]; then
  gdb -q -n -batch -ex "attach $PID" -ex "call (int)exit(0)" -ex "detach" -ex "quit" >/dev/null 2>&1
fi
