#!/usr/bin/env bash
# Prints "Best School" 10 times; on 9th iteration also prints "Hi"

counter=1

while [ $counter -le 10 ]
do
  echo "Best School"
  if [ $counter -eq 9 ]; then
    echo "Hi"
  fi
  counter=$((counter + 1))
done
