#!/usr/bin/env bash
# Displays numbers 1 to 20 with special bad luck messages using case statement

counter=1

while [ $counter -le 20 ]
do
  echo "$counter"
  case $counter in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  counter=$((counter + 1))
done
